use std::io::Write;
use std::path::PathBuf;
use std::process::ExitCode;

use clap::{Parser, Subcommand};

use jjr::claude::{self, ClaudeOutcome};
use jjr::error::JjrError;
use jjr::jj;
use jjr::packet;
use jjr::stack::{ResolvedStack, RevsetHash, StackEntry};
use jjr::store;
use jjr::tui;
use jjr::util::pluralize;
use jjr::working_copy_guard::WorkingCopyGuard;

#[derive(Parser)]
#[command(name = "jjr")]
#[command(about = "Local terminal review surface for jj stacks generated by an agent")]
#[command(version)]
struct Cli {
    /// Revset or change ID to review as a single change.
    /// Accepts any jj revset expression, including `@`, `@-`, branch names, or
    /// change IDs. When omitted, `jjr` walks the full stack (same as
    /// `--stack`).
    #[arg(conflicts_with = "stack")]
    change: Option<String>,

    /// Walk the full local stack (`trunk()..@`). This is the default when no
    /// change argument is given; the flag is available for explicit invocation.
    /// Resumes from the last cursor position; use `--restart` to start over.
    #[arg(long)]
    stack: bool,

    /// Clear the saved cursor for this stack and start from the oldest change.
    /// Only meaningful with `--stack`.
    #[arg(long, requires = "stack")]
    restart: bool,

    #[command(subcommand)]
    command: Option<Command>,
}

#[derive(Subcommand)]
enum Command {
    /// Remove comments matching the given filter from the resolved revset.
    Clear {
        /// Revset to operate on. Accepts any jj revset (`@`, `@-`, branch
        /// names, `trunk()..@`, etc.).
        revset: String,

        /// Clear line-scoped comments whose anchoring failed (status=stale).
        /// At least one filter flag is required.
        #[arg(long)]
        stale: bool,
    },

    /// Generate a Claude prompt from the review comments for the given revset.
    Packet {
        /// Revset to package. Defaults to `trunk()..@` (the full stack).
        revset: Option<String>,

        /// Write to file instead of stdout.
        #[arg(short = 'o', long)]
        output: Option<PathBuf>,

        /// Include comments marked stale. Orphaned comments are never included.
        #[arg(long)]
        include_stale: bool,
    },

    /// Generate a review packet and invoke Claude CLI to address the comments.
    ///
    /// The working copy is moved to the target change for Claude's session and
    /// restored to its prior position on exit, regardless of outcome.
    Claude {
        /// Revset / change to send to Claude. Resolves to exactly one change.
        /// Defaults to `@`.
        revset: Option<String>,

        /// Include comments marked stale. Orphaned comments are never included.
        #[arg(long)]
        include_stale: bool,
    },
}

fn main() -> ExitCode {
    let cli = Cli::parse();

    let result = match cli.command {
        Some(Command::Clear { revset, stale }) => run_clear(&revset, stale),
        Some(Command::Packet {
            revset,
            output,
            include_stale,
        }) => {
            let effective = revset.unwrap_or_else(|| jj::DEFAULT_STACK_REVSET.to_owned());
            return run_packet(&effective, output.as_deref(), include_stale);
        }
        Some(Command::Claude {
            revset,
            include_stale,
        }) => {
            let effective = revset.unwrap_or_else(|| "@".to_owned());
            return run_claude(&effective, include_stale);
        }
        None => match cli.change {
            None => run_stack(jj::DEFAULT_STACK_REVSET, cli.restart),
            Some(ref revset) => run_single(revset),
        },
    };

    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(err) => {
            print_error(&err);
            ExitCode::FAILURE
        }
    }
}

fn run_packet(revset: &str, output: Option<&std::path::Path>, include_stale: bool) -> ExitCode {
    let result = (|| -> Result<(), JjrError> {
        let repo_root = std::env::current_dir().map_err(|source| JjrError::Io { source })?;
        let resolved = jj::resolve_stack(revset)?;
        let pkt = packet::build_packet(
            &repo_root,
            revset,
            &resolved,
            include_stale,
            jj::diff_for_change,
        )?;
        let prompt = packet::render_prompt(&pkt);
        if let Some(path) = output {
            std::fs::write(path, &prompt).map_err(|source| JjrError::Io { source })
        } else {
            let mut stdout = std::io::stdout().lock();
            stdout
                .write_all(prompt.as_bytes())
                .map_err(|source| JjrError::Io { source })
        }
    })();

    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(JjrError::EmptyPacket { .. }) => {
            let mut stderr = std::io::stderr().lock();
            let _ = writeln!(stderr, "no comments to send");
            ExitCode::from(2)
        }
        Err(err) => {
            print_error(&err);
            ExitCode::FAILURE
        }
    }
}

fn run_claude(revset: &str, include_stale: bool) -> ExitCode {
    let result = (|| -> Result<(), JjrError> {
        let repo_root = std::env::current_dir().map_err(|source| JjrError::Io { source })?;
        let change_id = jj::resolve_revset(revset)?;
        let details = jj::show(&change_id)?;

        let resolved = ResolvedStack {
            revset_hash: RevsetHash::from_revset(revset),
            revset: revset.to_owned(),
            entries: vec![StackEntry {
                change_id: change_id.clone(),
                commit_id: details.commit_id,
                description: details.description,
            }],
        };

        let pkt = packet::build_packet(
            &repo_root,
            revset,
            &resolved,
            include_stale,
            jj::diff_for_change,
        )?;
        let prompt = packet::render_prompt(&pkt);

        let _guard = WorkingCopyGuard::enter(&repo_root, &change_id)?;
        match claude::invoke_claude(&prompt)? {
            ClaudeOutcome::Success => Ok(()),
            ClaudeOutcome::Failed { exit_code } => Err(JjrError::ClaudeFailed { exit_code }),
        }
    })();

    match result {
        Ok(()) => {
            let mut stderr = std::io::stderr().lock();
            let _ = writeln!(
                stderr,
                "claude completed; re-run `jjr` to review the result"
            );
            ExitCode::SUCCESS
        }
        Err(JjrError::EmptyPacket { .. }) => {
            let mut stderr = std::io::stderr().lock();
            let _ = writeln!(stderr, "no comments to send");
            ExitCode::from(2)
        }
        Err(err) => {
            print_error(&err);
            ExitCode::FAILURE
        }
    }
}

fn run_single(revset: &str) -> Result<(), JjrError> {
    let repo_root = std::env::current_dir().map_err(|source| JjrError::Io { source })?;
    let change_id = jj::resolve_revset(revset)?;
    tui::run(&change_id, &repo_root)
}

fn run_stack(revset: &str, restart: bool) -> Result<(), JjrError> {
    let repo_root = std::env::current_dir().map_err(|source| JjrError::Io { source })?;
    let resolved = jj::resolve_stack(revset)?;
    tui::run_stack(&repo_root, &resolved, restart)
}

fn run_clear(revset: &str, stale: bool) -> Result<(), JjrError> {
    if !stale {
        return Err(JjrError::NoFilterSpecified);
    }
    let repo_root = std::env::current_dir().map_err(|source| JjrError::Io { source })?;
    let resolved = jj::resolve_stack(revset)?;
    let stats = store::clear_stale_for_stack(&repo_root, &resolved)?;
    let mut stderr = std::io::stderr().lock();
    let _ = writeln!(
        stderr,
        "cleared {} stale {} across {} {}",
        stats.comments_removed,
        pluralize("comment", stats.comments_removed),
        stats.changes_touched,
        pluralize("change", stats.changes_touched),
    );
    Ok(())
}

fn print_error(err: &JjrError) {
    let mut stderr = std::io::stderr().lock();
    let _ = writeln!(stderr, "\x1b[1;31merror\x1b[0m {err}");
}
