use std::fmt::Display;
use std::io::Write;
use std::path::PathBuf;
use std::process::ExitCode;

use clap::{Parser, Subcommand};

use jjr::claude::{self, ClaudeOutcome};
use jjr::error::JjrError;
use jjr::export::{self, ExportFormat};
use jjr::jj;
use jjr::packet;
use jjr::stack::{ResolvedStack, RevsetHash, StackEntry};
use jjr::store;
use jjr::tui;
use jjr::util::{confirm_response, find_repo_root, pluralize};
use jjr::working_copy_guard::WorkingCopyGuard;

#[derive(Parser)]
#[command(name = "jjr")]
#[command(about = "Local terminal review surface for jj stacks generated by an agent")]
#[command(version)]
struct Cli {
    /// Revset or change ID to review as a single change.
    /// Accepts any jj revset expression, including `@`, `@-`, branch names, or
    /// change IDs. When omitted, `jjr` walks the full stack (same as
    /// `--stack`).
    #[arg(conflicts_with = "stack")]
    change: Option<String>,

    /// Walk the full local stack (`trunk()..@`). This is the default when no
    /// change argument is given; the flag is available for explicit invocation.
    /// Resumes from the last cursor position; use `--restart` to start over.
    #[arg(long)]
    stack: bool,

    /// Clear the saved cursor for this stack and start from the oldest change.
    /// Only meaningful with `--stack`.
    #[arg(long, requires = "stack")]
    restart: bool,

    #[command(subcommand)]
    command: Option<Command>,
}

#[derive(Subcommand)]
enum Command {
    /// Export all comments for the resolved revset to stdout.
    Export {
        /// Revset to export. Defaults to `trunk()..@`.
        revset: Option<String>,

        /// Output format.
        #[arg(long, default_value_t = ExportFormat::Jsonl)]
        format: ExportFormat,
    },

    /// Remove comments matching the given filter from the resolved revset.
    ///
    /// With no filter flag, clears ALL comments for the revset (with a
    /// confirmation prompt unless `--yes` is passed).
    Clear {
        /// Revset to operate on. Accepts any jj revset (`@`, `@-`, branch
        /// names, `trunk()..@`, etc.).
        revset: String,

        /// Clear line-scoped comments whose anchoring failed (status=stale).
        /// Mutually exclusive with `--orphaned`.
        #[arg(long, conflicts_with = "orphaned")]
        stale: bool,

        /// Clear comments for change IDs not present in the resolved revset
        /// (orphaned changes left behind after abandon/rebase). Mutually
        /// exclusive with `--stale`.
        #[arg(long)]
        orphaned: bool,

        /// Skip the confirmation prompt when clearing all comments.
        #[arg(long, short = 'y')]
        yes: bool,
    },

    /// Generate a Claude prompt from the review comments for the given revset.
    Packet {
        /// Revset to package. Defaults to `trunk()..@` (the full stack).
        revset: Option<String>,

        /// Write to file instead of stdout.
        #[arg(short = 'o', long)]
        output: Option<PathBuf>,

        /// Include comments marked stale. Orphaned comments are never included.
        #[arg(long)]
        include_stale: bool,
    },

    /// Generate a review packet and invoke Claude CLI to address the comments.
    ///
    /// The working copy is moved to the target change for Claude's session and
    /// restored to its prior position on exit, regardless of outcome.
    Claude {
        /// Revset / change to send to Claude. Resolves to exactly one change.
        /// Defaults to `@`.
        revset: Option<String>,

        /// Include comments marked stale. Orphaned comments are never included.
        #[arg(long)]
        include_stale: bool,
    },
}

fn main() -> ExitCode {
    let cli = Cli::parse();

    let result = match cli.command {
        Some(Command::Export { revset, format }) => {
            let effective = revset.unwrap_or_else(|| jj::DEFAULT_STACK_REVSET.to_owned());
            return run_export(&effective, format);
        }
        Some(Command::Clear {
            revset,
            stale,
            orphaned,
            yes,
        }) => run_clear(&revset, stale, orphaned, yes),
        Some(Command::Packet {
            revset,
            output,
            include_stale,
        }) => {
            let effective = revset.unwrap_or_else(|| jj::DEFAULT_STACK_REVSET.to_owned());
            return run_packet(&effective, output.as_deref(), include_stale);
        }
        Some(Command::Claude {
            revset,
            include_stale,
        }) => {
            let effective = revset.unwrap_or_else(|| "@".to_owned());
            return run_claude(&effective, include_stale);
        }
        None => match cli.change {
            None => run_stack(jj::DEFAULT_STACK_REVSET, cli.restart),
            Some(ref revset) => run_single(revset),
        },
    };

    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(JjrError::ClearAborted) => {
            let mut stderr = std::io::stderr().lock();
            let _ = writeln!(stderr, "clear aborted");
            ExitCode::from(1)
        }
        Err(err) => {
            print_error(&err);
            ExitCode::FAILURE
        }
    }
}

fn run_export(revset: &str, format: ExportFormat) -> ExitCode {
    let result = (|| -> Result<(), JjrError> {
        let repo_root = find_repo_root()?;
        let resolved = jj::resolve_stack(revset)?;
        let data = export::collect_export_data(&repo_root, &resolved)?;
        if export::is_empty(&data) {
            return Err(JjrError::NoCommentsToExport {
                revset: revset.to_owned(),
            });
        }
        let output = match format {
            ExportFormat::Jsonl => export::render_export_jsonl(&data)?,
            ExportFormat::Markdown => export::render_export_markdown(&data),
        };
        let mut stdout = std::io::stdout().lock();
        stdout
            .write_all(output.as_bytes())
            .map_err(|source| JjrError::Io { source })
    })();

    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(JjrError::NoCommentsToExport { .. }) => {
            let mut stderr = std::io::stderr().lock();
            let _ = writeln!(stderr, "no comments to export");
            ExitCode::from(2)
        }
        Err(err) => {
            print_error(&err);
            ExitCode::FAILURE
        }
    }
}

fn run_packet(revset: &str, output: Option<&std::path::Path>, include_stale: bool) -> ExitCode {
    let result = (|| -> Result<(), JjrError> {
        let repo_root = find_repo_root()?;
        let resolved = jj::resolve_stack(revset)?;
        let pkt = packet::build_packet(
            &repo_root,
            revset,
            &resolved,
            include_stale,
            jj::diff_for_change,
        )?;
        let prompt = packet::render_prompt(&pkt);
        if let Some(path) = output {
            std::fs::write(path, &prompt).map_err(|source| JjrError::Io { source })
        } else {
            let mut stdout = std::io::stdout().lock();
            stdout
                .write_all(prompt.as_bytes())
                .map_err(|source| JjrError::Io { source })
        }
    })();

    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(JjrError::EmptyPacket { .. }) => {
            let mut stderr = std::io::stderr().lock();
            let _ = writeln!(stderr, "no comments to send");
            ExitCode::from(2)
        }
        Err(err) => {
            print_error(&err);
            ExitCode::FAILURE
        }
    }
}

fn run_claude(revset: &str, include_stale: bool) -> ExitCode {
    let result = (|| -> Result<(), JjrError> {
        let repo_root = find_repo_root()?;
        let change_id = jj::resolve_revset(revset)?;
        let details = jj::show(&change_id)?;

        let resolved = ResolvedStack {
            revset_hash: RevsetHash::from_revset(revset),
            revset: revset.to_owned(),
            entries: vec![StackEntry {
                change_id: change_id.clone(),
                commit_id: details.commit_id,
                description: details.description,
            }],
        };

        let pkt = packet::build_packet(
            &repo_root,
            revset,
            &resolved,
            include_stale,
            jj::diff_for_change,
        )?;
        let prompt = packet::render_prompt(&pkt);

        let _guard = WorkingCopyGuard::enter(&repo_root, &change_id)?;
        match claude::invoke_claude(&prompt)? {
            ClaudeOutcome::Success => Ok(()),
            ClaudeOutcome::Failed { exit_code } => Err(JjrError::ClaudeFailed { exit_code }),
        }
    })();

    match result {
        Ok(()) => {
            let mut stderr = std::io::stderr().lock();
            let _ = writeln!(
                stderr,
                "claude completed; re-run `jjr` to review the result"
            );
            ExitCode::SUCCESS
        }
        Err(JjrError::EmptyPacket { .. }) => {
            let mut stderr = std::io::stderr().lock();
            let _ = writeln!(stderr, "no comments to send");
            ExitCode::from(2)
        }
        Err(err) => {
            print_error(&err);
            ExitCode::FAILURE
        }
    }
}

fn run_single(revset: &str) -> Result<(), JjrError> {
    let repo_root = find_repo_root()?;
    let change_id = jj::resolve_revset(revset)?;
    tui::run(&change_id, &repo_root)
}

fn run_stack(revset: &str, restart: bool) -> Result<(), JjrError> {
    let repo_root = find_repo_root()?;
    let resolved = jj::resolve_stack(revset)?;
    tui::run_stack(&repo_root, &resolved, restart)
}

fn run_clear(revset: &str, stale: bool, orphaned: bool, yes: bool) -> Result<(), JjrError> {
    let repo_root = find_repo_root()?;
    let resolved = jj::resolve_stack(revset)?;

    if stale {
        let stats = store::clear_stale_for_stack(&repo_root, &resolved)?;
        print_clear_summary(stats.comments_removed, Some("stale"), stats.changes_touched);
        return Ok(());
    }

    if orphaned {
        let stats = store::clear_orphaned_for_revset(&repo_root, &resolved)?;
        print_clear_summary(
            stats.comments_removed,
            Some("orphaned"),
            stats.changes_touched,
        );
        return Ok(());
    }

    // Bare clear — confirm unless --yes.
    let total = store::count_all_for_stack(&repo_root, &resolved)?;
    if total == 0 {
        let mut stderr = std::io::stderr().lock();
        let _ = writeln!(stderr, "no comments to clear");
        return Ok(());
    }
    if !yes {
        let mut stderr = std::io::stderr().lock();
        let _ = writeln!(
            stderr,
            "Clear {} {}? [y/N]",
            total,
            pluralize("comment", total)
        );
        drop(stderr);

        let mut line = String::new();
        std::io::stdin()
            .read_line(&mut line)
            .map_err(|source| JjrError::Io { source })?;
        if !confirm_response(&line) {
            return Err(JjrError::ClearAborted);
        }
    }

    let stats = store::clear_all_for_stack(&repo_root, &resolved)?;
    print_clear_summary(stats.comments_removed, None, stats.changes_touched);
    Ok(())
}

/// Print a summary line to stderr: "cleared N stale comments across M changes".
///
/// `qualifier` is `Some("stale")`, `Some("orphaned")`, or `None` for bare clear.
fn print_clear_summary(removed: usize, qualifier: Option<&str>, changes_touched: usize) {
    let mut stderr = std::io::stderr().lock();
    match qualifier {
        None => {
            let _ = writeln!(
                stderr,
                "cleared {} {} across {} {}",
                removed,
                pluralize("comment", removed),
                changes_touched,
                pluralize("change", changes_touched),
            );
        }
        Some(q) => {
            let _ = writeln!(
                stderr,
                "cleared {} {} {} across {} {}",
                removed,
                q,
                pluralize("comment", removed),
                changes_touched,
                pluralize("change", changes_touched),
            );
        }
    }
}

fn print_error(err: &dyn Display) {
    let mut stderr = std::io::stderr().lock();
    let _ = writeln!(stderr, "\x1b[1;31merror\x1b[0m {err}");
}
