use std::io::Write;
use std::process::ExitCode;

use clap::Parser;

use jjr::error::JjrError;
use jjr::jj;
use jjr::tui;

#[derive(Parser)]
#[command(name = "jjr")]
#[command(about = "Local terminal review surface for jj stacks generated by an agent")]
#[command(version)]
struct Cli {
    /// Revset to review. Omit to review the current change (`@`).
    /// Accepts any jj revset expression, including `@`, `@-`, branch names, or
    /// change IDs.
    change: Option<String>,
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    let revset = cli.change.unwrap_or_else(|| "@".to_owned());

    match run(&revset) {
        Ok(()) => ExitCode::SUCCESS,
        Err(err) => {
            print_error(&err);
            ExitCode::FAILURE
        }
    }
}

fn run(revset: &str) -> Result<(), JjrError> {
    let change_id = jj::resolve_revset(revset)?;
    tui::run(&change_id)
}

fn print_error(err: &JjrError) {
    let mut stderr = std::io::stderr().lock();
    let _ = writeln!(stderr, "\x1b[1;31merror\x1b[0m {err}");
}
